version: '3'
 
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432
    # dynamodb-local:
    #   image: amazon/dynamodb-local
    #   command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
    #   ports:
    #   - 8000:8000