version: '3'
 
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432
  localstack:
    image: localstack/localstack:0.11.4
    environment:
      - SERVICES=s3:5000
      - DEFAULT_REGION=
      - HOSTNAME=localhost
  dynamodblocal:
    image: amazon/dynamodb-local
    networks:
      - default
    ports:
      - 8000:8000