// <auto-generated />
using DbMigration.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbMigration.Migrations
{
    [DbContext(typeof(_MyDbContext))]
    partial class _MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbMigration.Entity.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("選手ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("選手名");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasComment("ポジション");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasComment("学校ID");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasComment("チームID");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("DbMigration.Entity.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("学校ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("学校名");

                    b.HasKey("Id");

                    b.ToTable("School", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "パワフル高校"
                        },
                        new
                        {
                            Id = 2,
                            Name = "あかつき高校"
                        },
                        new
                        {
                            Id = 3,
                            Name = "帝王高校"
                        });
                });

            modelBuilder.Entity("DbMigration.Entity.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("チームID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("チーム名");

                    b.HasKey("Id");

                    b.ToTable("Team", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "巨人"
                        },
                        new
                        {
                            Id = 2,
                            Name = "阪神"
                        },
                        new
                        {
                            Id = 3,
                            Name = "中日"
                        });
                });

            modelBuilder.Entity("DbMigration.Entity.Player", b =>
                {
                    b.HasOne("DbMigration.Entity.School", "School")
                        .WithMany("Player")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigration.Entity.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DbMigration.Entity.School", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("DbMigration.Entity.Team", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
