// <auto-generated />
using Entity.MyDbContext.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Entity.MyDbContext.Migrations
{
    [DbContext(typeof(_MyDbContext))]
    [Migration("20220314153511_InitTables")]
    partial class InitTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Entity.MyDbContext.Entity.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("選手ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("選手名");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasComment("ポジション");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasComment("学校ID");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasComment("チームID");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Entity.MyDbContext.Entity.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("学校ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("学校名");

                    b.HasKey("Id");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "パワフル高校"
                        },
                        new
                        {
                            Id = 2,
                            Name = "あかつき高校"
                        },
                        new
                        {
                            Id = 3,
                            Name = "帝王高校"
                        });
                });

            modelBuilder.Entity("Entity.MyDbContext.Entity.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("チームID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("チーム名");

                    b.HasKey("Id");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "巨人"
                        },
                        new
                        {
                            Id = 2,
                            Name = "阪神"
                        },
                        new
                        {
                            Id = 3,
                            Name = "中日"
                        });
                });

            modelBuilder.Entity("Entity.MyDbContext.Entity.Player", b =>
                {
                    b.HasOne("Entity.MyDbContext.Entity.School", "School")
                        .WithMany("Player")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.MyDbContext.Entity.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Entity.MyDbContext.Entity.School", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("Entity.MyDbContext.Entity.Team", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
